# Generated by Django 6.0.1 on 2026-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='is_early_adopter',
            field=models.BooleanField(default=False, help_text='Flag for early adopters'),
        ),
    ]
