# Generated by Django 6.0.1 on 2026-02-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentwebhooklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patron_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
