# Generated by Django 6.0.1 on 2026-02-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_patron_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patron_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
