# Generated by Django 6.0.1 on 2026-04-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creators', '0003_creatorprofile_is_early_adopter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('next_payout_date', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_schedules', to='creators.creatorprofile')),
            ],
        ),
    ]
